---
- name: Execute Script
  hosts: VM_Host*
  tasks:
    - name: create a text file in $HOME with the /bin/sh shell
      shell: echo "Hello, World!" > $HOME/test_file.txt
    - name: start automate thru exec
      ansible.windows.win_shell: 'C:\aocc\test.sh "argument 1" -force'  