---
- name: Get tasklist
  hosts: VM_Host
  tasks:
    - name: List tasks
      ansible.windows.win_command:
        cmd: tasklist  /fi "IMAGENAME eq automate.exe"
    - name: run tasklist to find automata.exe
      raw: tasklist  /fi "IMAGENAME eq automate.exe"
      register: tlist
    - debug: var=tlist
    - name: kill automata.exe
      raw: taskkill /F /fi "IMAGENAME eq automate.exe"
      register: tkill
    - debug: var=tkill
    - name: to start bp
      raw: Start-Process -FilePath “Automate.exe” -WorkingDirectory ‘C:\Program
        Files\Blue Prism Limited\Blue Prism Automate\’  -ArgumentList
        “/resourcepc”,“/public”
      register: tstart
      ignore_errors: yes
    - debug: var=tstart
    - name: start automate thru exec
      ansible.windows.win_shell: Start-Process -FilePath “Automate.exe” -WorkingDirectory ‘C:\Program
        Files\Blue Prism Limited\Blue Prism Automate\’  -ArgumentList
        “/resourcepc”,“/public”
      args:
        -executable: powershell
      register: homedir_out
      ignore_errors: yes
    - debug: var=homedir_out
    - name: start automate thru bat
      win_shell: C:\aocc\runserver.bat
      register: result
      ignore_errors: yes  
      become: false    
    - name: Display output
      debug:
        var: result.stdout_lines
    

     
   
