---
- name: Get tasklist
  hosts: VM_Host
  tasks:
    - name: List tasks
      ansible.windows.win_command:
        cmd: tasklist  /fi "IMAGENAME eq automate.exe"
    - name: run tasklist to find automata.exe
      raw: tasklist  /fi "IMAGENAME eq automate.exe"
      register: tlist
    - debug: var=tlist
    - name: kill automata.exe
      raw: taskkill /F /fi "IMAGENAME eq automate.exe"
      register: tkill
    - debug: var=tkill    
    - name: start automate thru exec
      ansible.windows.win_command:
      # When using cmd, the arguments need to be quoted manually
      cmd: '"C:\aocc\runserver.bat" "argument 1" -force'
      register: homedir_out
    - debug: var=homedir_out
    
   
    

     
   
