---
- name: Get tasklist
  hosts: VM_Host
  tasks:
    - name: List tasks
      ansible.windows.win_command:
        cmd: tasklist  /fi "IMAGENAME eq automate.exe"
    - name: run tasklist to find automata.exe
      raw: tasklist  /fi "IMAGENAME eq automate.exe"
      register: tlist
    - debug: var=tlist
    - name: kill automata.exe
      raw: taskkill /F /fi "IMAGENAME eq automate.exe"
      register: tkill
    - debug: var=tkill
    - name: to start bp
      raw: Start-Process -FilePath “Automate.exe” -WorkingDirectory ‘C:\Program
        Files\Blue Prism Limited\Blue Prism Automate\’  -ArgumentList
        “/resourcepc”,“/public”
      register: tstart
    - debug: var=tstart
    - name: start automate thru exec
      ansible.windows.win_shell: echo %HOMEDIR%
      args:
      executable: cmd
      register: homedir_out
    - debug: var=homedir_out

     
   
