---
- name: Get tasklist
  hosts: VM_Host
  tasks:
    - name: List tasks
      ansible.windows.win_command:
        cmd: tasklist  /fi "IMAGENAME eq automate.exe"
    - name: run tasklist to find automata.exe
      raw: tasklist  /fi "IMAGENAME eq automate.exe"
      register: tlist
    - debug: var=tlist
    - name: kill automata.exe
      raw: taskkill /F /fi "IMAGENAME eq automate.exe"
      register: tkill
    - debug: var=tkill
    - name: to start bp
      raw: Start-Process -FilePath “Automate.exe” -WorkingDirectory ‘C:\Program
        Files\Blue Prism Limited\Blue Prism Automate\’  -ArgumentList
        “/resourcepc”,“/public”
      register: tstart
    - debug: var=tstart
    - name: to start notepad
      raw: Start-Process -FilePath "notepad.exe” -WorkingDirectory
        ‘C:\Users\snchapar\AppData\Roaming\Microsoft\Windows\Start
        Menu\Programs\Accessories\’  -ArgumentList “/resourcepc”,“/public”
      register: tnote
    - debug: var=tnote
