- name: Get tasklist
  hosts: VM_Host
  tasks: 
    - name: List tasks
      ansible.windows.win_command: 
        cmd: 'tasklist  /fi "IMAGENAME eq automate.exe"'    
    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
    - debug: var=ipconfig
    - name: run tasklist to find automata.exe
      raw: tasklist  /fi "IMAGENAME eq automate.exe" 
      register: tlist
    - debug: var=tlist